<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <!-- Spring Boot Parent -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.14</version>
        <relativePath/>
    </parent>

    <!-- Project Details -->
    <groupId>com.bank</groupId>
    <artifactId>banking-platform-microservices</artifactId>
    <version>1.0.0</version>

    <!-- Important for Parent Maven Project -->
    <packaging>pom</packaging>

    <!-- Common Properties -->
    <properties>
        <java.version>21</java.version>
    </properties>

    <!-- Microservice Modules -->
    <modules>
        <module>services/auth-service</module>
        <module>services/customer-service</module>
        <module>services/account-service</module>
        <module>services/transaction-service</module>
        <!--  <module>services/payment-service</module>
         <module>services/loan-service</module>
         <module>services/notification-service</module>
         <module>services/audit-service</module>
         <module>services/reporting-service</module>
         <module>services/api-gateway</module>
         -->

    </modules>

</project>