spring.application.name=account-service

server.port=8083

spring.datasource.url=jdbc:h2:file:./data/accountdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=TXlWZXJ5U2VjcmV0S2V5Rm9ySnd0QXV0aGVudGljYXRpb25NeVZlcnlTZWNyZXRLZXk=
jwt.expiration=86400000